twig:
    form_themes: ['bootstrap_5_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'

    globals:
        user_service: '@App\Service\UserService'
        category_service: '@App\Service\CategoryService'
        topic_service: '@App\Service\TopicService'
        # message_service: '@App\Service\MessageService'


when@test:
    twig:
        strict_variables: true
